<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>CREATE USER</title>\n";
echo "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\" integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n";
echo "    <link rel=\"stylesheet\" href=\"createuser.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <div class=\"container\">\n";
echo "        <table class=\"_table\">\n";
echo "           <thead>\n";
echo "            <tr>\n";
echo "                <th>First Name</th>\n";
echo "                <th>Middle Name</th>\n";
echo "                <th>Last Name</th>\n";
echo "                <th>Username</th>\n";
echo "                <th>Email Address</th>\n";
echo "                <th>Unique ID</th>\n";
echo "                <th>Password</th>\n";
echo "                <th>Type</th>\n";
echo "                <th width=\"50px\">\n";
echo "                    <div class=\"action_container\">\n";
echo "                        <button class=\"success\" onclick=\"create_tr(\'table_body\')\">\n";
echo "                            <i class=\"fa-solid fa-plus\"></i>\n";
echo "                        </button>\n";
echo "                    </div>\n";
echo "                </th>\n";
echo "            </tr>\n";
echo "           </thead>\n";
echo "           <tbody id=\"table_body\">\n";
echo "                <tr>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"Juan\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"reyes\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"dela cruz\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"jdcruz01\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"jdcruz01\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"jdcruz01\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"jdcruz01\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <input type=\"text\" class=\"form_control\" placeholder=\"jdcruz01\">\n";
echo "                    </td>\n";
echo "                    <td>\n";
echo "                        <div class=\"action_container\">\n";
echo "                            <button class=\"danger\" onclick=\"remove_tr(this)\">\n";
echo "                                <i class=\"fa-solid fa-trash\"></i>\n";
echo "                            </button>\n";
echo "                        </div>\n";
echo "                    </td>\n";
echo "                </tr>\n";
echo "           </tbody>\n";
echo "        </table>\n";
echo "    </div>\n";
echo "    <script src=\"createuser.js\"></script>\n";
echo "    \n";
echo "</body>\n";
echo "</html>\n";
?>